# roles/redhat_idm/tasks/reporting/main.yaml

---
- name: Global execution
  block:
  - name: Define default vars for this sub-role
    ansible.builtin.set_fact:
      mail_subject: "[LAF] IPA Reporting"
      mail_content: |-
        {{ __mail_header }}
        <br>
        <br>
        <div style="border: 1px solid #333; padding: 8px; text-align: center; border-radius: 5px; margin-bottom: 10px; background-color: #f9f9f9;">
          <b style="font-size: 1.5em;">Execution informations</b>
        </div>
      run_unique_id: "{{ lookup('password', '/dev/null length=10 chars=digits') }}"

  - name: Include create working_dir tasks
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/utils/create_working_dir.yaml"

  - name: Include set of tasks to create selected IPA dict
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/utils/define_select_ipa_dict.yaml"

  - name: Define mail subject
    ansible.builtin.set_fact:
      mail_subject: "[LAF] IPA Reporting - Global reporting"

  ############################################
  #  Loop on selected IPAs                   #
  ############################################

  - name: Fetch data and generate XLSX per IPA
    ansible.builtin.include_tasks: fetch/loop_on_ipa.yaml
    loop: "{{ selected_ipa | dict2items }}"
    loop_control:
      loop_var: current_ipa
      label: "{{ current_ipa.key }}"

  rescue:
  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        An error occur during execution, please forward this mail to cso-linux@deep.eu

  always:
  - block:
    - name: Find all XLSX reports to attach
      ansible.builtin.find:
        paths: "{{ working_dir }}"
        patterns: "*.xlsx"
      register: report_files

    - name: Send execution result by mail
      community.general.mail:
        host: "localhost"
        port: "25"
        sender: "{{ __mail_from }}"
        to: "{{ mail_recipient }}"
        subject: "{{ mail_subject }}"
        body: "{{ mail_content }}"
        attach: "{{ report_files.files | map(attribute='path') | list }}"
        charset: utf8
        subtype: html
      loop: "{{ __mail_to }}"
      loop_control:
        loop_var: mail_recipient
      when: report_files.matched > 0

    always:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/utils/clean_working_dir.yaml"
