# roles/redhat_idm/tasks/manage/users/add_group/loop_on_groups.yaml

---
- name: Include add to group tasks
  ansible.builtin.include_tasks: add_to_group.yaml

- name: Append result to rows
  ansible.builtin.set_fact:
    result_rows: "{{ result_rows + [row] }}"
  vars:
    row:
      username: "{{ username }}"
      group: "{{ groupname }}"
      status: "{{ group_status }}"
      client_id: "{{ client_id }}"
      ipa_domain: "{{ ipa_domain }}"
