# roles/redhat_idm/tasks/manage/users/enabling/loop_on_ipa.yaml

---
- name: Deploy manage XLSX script
  delegate_to: localhost
  ansible.builtin.copy:
    src: "{{ role_path }}/files/generate_xlsx_manage.py"
    dest: "{{ working_dir }}/generate_xlsx_manage.py"
    mode: "0755"
  run_once: true

- block:
  - name: Failed if __username is empty
    ansible.builtin.fail:
      msg: "__username is empty, stopping execution."
    when: __username | length == 0

  - name: Loop on __username list
    ansible.builtin.include_tasks: loop_on_users.yaml
    loop: '{{ __username | split(";") }}'
    loop_control:
      loop_var: username
      label: "Sensitive data is hidden."

  rescue:
  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        The __username list cannot be empty, stopping execution.
