# roles/redhat_idm/tasks/manage/users/enabling/reset_password.yaml

---
- block:
  - name: Reset password for {{ username }}
    delegate_to: "{{ ipa_server }}"
    redhat.rhel_idm.ipauser:
      name: "{{ username }}"
      password: "{{ generated_password }}"
      update_password: always
      ipaadmin_principal: "{{ ipa_user }}"
      ipaadmin_password: "{{ ipa_pass }}"
    register: password_reset_result

  - name: Set user_status after password reset (enabling workflow)
    ansible.builtin.set_fact:
      user_status: "{{ user_status | default('Enabled') }}"

  - name: Update mail_content based on password reset status
    ansible.builtin.set_fact:
      mail_content: |
        {{ mail_content }}
        {{ ipa_domain }} - {{ username }} account password has been correctly reset.<br>

  rescue:
  - name: Set user_status on password reset error (enabling workflow)
    ansible.builtin.set_fact:
      user_status: >-
        {% if password_reset_result.msg is defined and password_reset_result.msg == 'First name is needed' %}
        Not found
        {% else %}
        Error: {{ password_reset_result.msg | default(ansible_failed_result.msg | default('Unknown error')) | truncate(120) }}
        {% endif %}

  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        <b>{{ ipa_domain }} - ⚠️ Failed to reset {{ username | default('username-var') }} account password.</b><br>
          <pre style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ccc;">
          {% if password_reset_result.msg is defined and password_reset_result.msg == 'First name is needed' %}
          {{ username }} doesn't exist on this IPA server.
          {% else %}
          {{ password_reset_result.msg | default(ansible_failed_result.msg | default('No msg captured')) }}
          {% endif %}
          </pre>
