# roles/datadog_agent/tasks/main.yaml

---
- ansible.builtin.include_tasks: installation/main.yaml
  when: INSTALL_DATADOG_AGENT | default(false)

- ansible.builtin.include_tasks: remove/main.yaml
  when: REMOVE_DATADOG_AGENT | default(false)
