# roles/redhat_idm/tasks/main.yaml

---
- name: Include IPA setup tasks
  ansible.builtin.include_tasks: setup/main.yaml
  when: REDHAT_IDM_INIT | default(false)

- name: Include IPA management tasks
  ansible.builtin.include_tasks: manage/main.yaml
  when: REDHAT_IDM_MANAGING | default(false)

- name: Include IPA reporting tasks
  ansible.builtin.include_tasks: reporting/main.yaml
  when: REDHAT_IDM_REPORTING | default(false)
