# roles/redhat_idm/tasks/main.yaml

---
- name: Include IPA cluster installation tasks
  ansible.builtin.include_tasks: setup/cluster_install/main.yaml
  when: REDHAT_IDM_CLUSTER_INSTALL | default(false)

- name: Include IPA data provisioning tasks
  ansible.builtin.include_tasks: setup/data_provisioning/main.yaml
  when: REDHAT_IDM_DATA_PROVISIONING | default(false)

- name: Include IPA management tasks
  ansible.builtin.include_tasks: manage/main.yaml
  when: REDHAT_IDM_MANAGING | default(false)

- name: Include IPA reporting tasks
  ansible.builtin.include_tasks: reporting/main.yaml
  when: REDHAT_IDM_REPORTING | default(false)
