# roles/tools/tasks/server_add_memory/vcenter/00_main.yaml

---
- name: "VCENTER | Reset loop breaker"
  ansible.builtin.set_fact:
    vcenter_action_done: false

- name: "VCENTER | Loop on each vCenter to {{ vcenter_action | upper }}"
  ansible.builtin.include_tasks:
    file: "{{ (vcenter_action == 'get_memory_info') | ternary('get_memory_info.yaml', 'extend_memory.yaml') }}"
  loop: "{{ __vcenter_infos | dict2items }}"
  loop_control:
    loop_var: current_vcenter
    label: "Sensitive data is hidden."