# roles/tools/tasks/server_manual_patching/vcenter/00_main.yaml

---
- name: "VCENTER | Reset loop breaker var"
  ansible.builtin.set_fact:
    vcenter_action_done: false

- name: "VCENTER | Loop on each vCenter to {{ vcenter_action | upper }} snapshot"
  ansible.builtin.include_tasks:
    file: "{{ (vcenter_action == 'create_snapshot') | ternary('01_create_snapshot.yaml', '02_delete_snapshot.yaml') }}"
  loop: "{{ __vcenter_infos | dict2items }}"
  loop_control:
    loop_var: current_vcenter
    label: "Sensitive data is hidden."
