# roles/redhat_idm/tasks/manage/users/deletion/03_delete_user.yaml

---
- block:
  - name: Delete IPA user {{ username }} on {{ ipa_server }}
    delegate_to: "{{ ipa_server }}"
    redhat.rhel_idm.ipauser:
      name: "{{ username }}"
      state: absent
      ipaadmin_principal: "{{ ipa_user }}"
      ipaadmin_password: "{{ ipa_pass }}"
    register: user_deletion_result

  - name: Update mail_content based on creation status
    ansible.builtin.set_fact:
      mail_content: |
        {{ mail_content }}
        {% if user_deletion_result.changed %}
        {{ ipa_domain }} - {{ username }} account has been correctly deleted.<br>
        {% else %}
        <b>{{ ipa_domain }} - {{ username }} account wasn't existing on this IPA.</b><br>
        {% endif %}

  rescue:
  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        <b>{{ ipa_domain }} - ⚠️ Failed to delete the {{ username | default('username-var') }} account.</b><br>
        <pre style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ccc;">
        {{ user_deletion_result.msg | default(['No msg captured']) }}
        </pre>
