---
- name: Install IdM cluster
  hosts: ipacluster
  become: true

# Usage
# You must use the utils/redhat_idm_prov.sh to generate initial ipa inventory
# ansible-playbook playbooks/managed_services/redhat_idm/setup/01_install_cluster.yaml -i clients/XXXX/ipa.ini

  vars:
    REDHAT_IDM_CLUSTER_INSTALL: true

  roles:
    - redhat_idm
