---
- name: Playbook for IPA Data provisioning
  hosts: ipaserver

# Usage
# ansible-playbook playbooks/managed_services/redhat_idm/setup/02_add_initial_data.yaml -i clients/XXXX/ipa.ini

  vars:
    REDHAT_IDM_INIT: true

  roles:
    - common
    - redhat_idm
