# roles/redhat_idm/defaults/main.yaml

---
# Vars to select IPA ou env to run
__clients_id_prompted: "" # Separate with a ;
__clients_id_excluded_prompted: "" # Separate with a ;
__target_environment: ""

# Var to override the zip encryption password
__use_internal_communication_password: false

# IdM setup / cluster installation
ipaadmin_principal: admin
redhat_idm_install_packages: true
redhat_idm_skip_prechecks: false
redhat_idm_disable_firewalld: true
