# roles/redhat_idm/defaults/main.yaml

---
# Vars to select IPA ou env to run
__clients_id_prompted: "" # Separate with a ;
__clients_id_excluded_prompted: "" # Separate with a ;
__target_environment: ""

# Var to override the zip encryption password
__use_internal_communication_password: false

# Creation role defaults (not survey vars — use 'usernames', 'user_firstname', etc. in survey)
__user_homefolder: "/home" # manage var
__user_default_shell: "/bin/bash" # manage var
