# roles/redhat_idm/tasks/setup/data_provisioning/tasks/02_pw_policies.yaml

---
- name: Set Password Policies
  redhat.rhel_idm.ipapwpolicy:
    name: 
      - "{{ item.key }}"
    maxlife: "{{ item.value.maxlifetime | string }}"
    minlife: "{{ item.value.minlifetime | string }}"
    history: "{{ item.value.history | string }}"
    minclasses: "{{ item.value.minclasses | string }}"
    minlength: "{{ item.value.minlength | string }}"
    maxfail: "{{ item.value.maxfail | string }}"
    failinterval: "{{ item.value.failinterval | string }}"
    lockouttime: "{{ item.value.lockouttime | string }}"
    priority: "{{ item.value.priority | string }}"
    ipaadmin_password: "{{ ipaadmin_password }}"
    state: present
  loop: "{{ password_policies | dict2items }}"
