# roles/elastic_agent/tasks/main.yaml

---
- ansible.builtin.include_tasks: install.yaml
  when: INSTALL_ELASTIC_AGENT | default(false)

- ansible.builtin.include_tasks: remove.yaml
  when: REMOVE_ELASTIC_AGENT | default(false)
