---
- name: Maintenance - Add more memory to a server (hot-add)
  hosts: all
  gather_facts: true
  become: true

# Dry-run
# ansible-playbook playbooks/tools/maintenance/server_add_memory.yaml -i host, -e "requested_memory_gb=8"

# Execute
# ansible-playbook playbooks/tools/maintenance/server_add_memory.yaml -i host, -e "auth_token=ABC123 requested_memory_gb=8"

  vars:
    ADD_MEMORY: true

  roles:
    - common
    - tools
