---
- name: Maintenance - Add more CPU to a server (hot-add)
  hosts: all
  gather_facts: true
  become: true

# Dry-run
# ansible-playbook playbooks/tools/maintenance/server_add_cpu.yaml -i sv-xxxxlvuxx.rh.xxxx.local, -e "requested_cpu_count=8"

# Execute
# ansible-playbook playbooks/tools/maintenance/server_add_cpu.yaml -i sv-xxxxlvuxx.rh.xxxx.local, -e "auth_token=XYZ123 requested_cpu_count=8"

  vars:
    ADD_CPU: true

  roles:
    - common
    - tools
