# roles/redhat_idm/tasks/manage/users/remove_group/02_loop_on_users.yaml

---
- name: Loop on __user_groups list
  ansible.builtin.include_tasks: loop_on_groups.yaml
  loop: "{{ __user_groups | replace(' ', ',') | split(',') }}"
  loop_control:
    loop_var: groupname
