# roles/redhat_idm/tasks/manage/users/remove_group/04_remove_from_group.yaml

---
- block:
  - name: Remove {{ username }} from {{ groupname }} group
    delegate_to: "{{ ipa_server }}"
    redhat.rhel_idm.ipagroup:
      ipaadmin_principal: "{{ ipa_user }}"
      ipaadmin_password: "{{ ipa_pass }}"
      name: "{{ groupname }}"
      user:
        - "{{ username }}"
      action: member
      state: absent
    register: remove_from_group_result

  - name: Update mail_content based on group removal status
    ansible.builtin.set_fact:
      mail_content: |
        {{ mail_content }}
        {% if remove_from_group_result.changed %}
        {{ ipa_domain }} - {{ username }} has correctly been removed from {{ groupname }} group.<br>
        {% else %}
        <b>{{ ipa_domain }} - {{ username }} wasn't in {{ groupname }} group.</b><br>
        {% endif %}

  rescue:
  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        <b>{{ ipa_domain }} - ⚠️ Failed to remove {{ username | default('username-var') }} from {{ groupname | default('groupname-var') }} group.</b><br>
        <pre style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ccc;">
        {{ remove_from_group_result.msg | default(ansible_failed_result.msg | default('Unknown error')) }}
        </pre>

