# roles/tools/tasks/server_pre_decom_start/vcenter/start_server.yaml

---
- name: "VCENTER | Power on block"
  delegate_to: localhost
  become: false
  when: not vcenter_action_done | default(false)
  block:
    - name: "VCENTER | Search VM"
      ansible.builtin.include_tasks:
        file: search_vm.yaml

    - name: "VCENTER | Power ON the VM"
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ current_vcenter.value.url }}"
        username: "{{ current_vcenter.value.username }}"
        password: "{{ current_vcenter.value.password }}"
        validate_certs: false
        datacenter: "{{ vm_details.datacenter }}"
        uuid: "{{ vm_details.uuid }}"
        state: powered-on
      register: vm_power_result

    - name: "VCENTER | Break loop"
      ansible.builtin.set_fact:
        vcenter_action_done: true

  rescue:
    - name: "VCENTER | VM not found on {{ current_vcenter.value.url }}"
      ansible.builtin.debug:
        msg: "VM {{ inventory_hostname_short | lower }} not found on {{ current_vcenter.value.url }}, moving to next vCenter..."