# roles/elastic_agent/tasks/installation/checks/01_already_installed.yaml

---
- name: "Gather package facts"
  ansible.builtin.package_facts:
    manager: auto
  become: yes

- name: "Gather service facts"
  ansible.builtin.service_facts:
  become: yes

- name: "Check if Elastic Agent is already present"
  ansible.builtin.set_fact:
    elastic_agent_exists: "{{ 'elastic-agent' in ansible_facts.packages or 'elastic-agent.service' in ansible_facts.services }}"

- name: "Report and skip host if Elastic Agent is already present"
  block:
    - name: "Display presence details"
      ansible.builtin.debug:
        msg: |
          INFO: Elastic Agent is already present. Skipping this host to prevent configuration overwrite.
          Details :
          - Installed via Package: {{ 'YES' if 'elastic-agent' in ansible_facts.packages else 'NO' }}
          - Service detected: {{ 'YES' if 'elastic-agent.service' in ansible_facts.services else 'NO' }}
          {% if 'elastic-agent.service' in ansible_facts.services %}
          - Service State: {{ ansible_facts.services['elastic-agent.service'].state }}
          - Service Status: {{ ansible_facts.services['elastic-agent.service'].status }}
          {% endif %}

    - name: "Stop execution"
      ansible.builtin.meta: end_host
  when: elastic_agent_exists

- name: "Confirm proceed for new installation"
  ansible.builtin.debug:
    msg: "ASSERT PASSED: No trace of elastic-agent package or service found. Proceeding with installation..."
