# roles/elastic_agent/tasks/installation/checks/02_service_exist.yaml

---
- name: "Check if Elastic Agent service is already installed"
  ansible.builtin.stat:
    path: /etc/systemd/system/elastic-agent.service
  register: agent_service_stat

- name: "Fail if elastic-agent already exists"
  ansible.builtin.fail:
    msg: "The Elastic Agent service file already exists. Stopping installation. We can't upgrade a Fleet managed elastic-agent deployment."
  when: agent_service_stat.stat.exists
