# roles/elastic_agent/tasks/installation/checks/05_tarball_content_is_present.yaml

---
- name: Check if directory exists
  ansible.builtin.stat:
    path: "{{ __tmp_elastic_directory }}"
  register: dir_stat

- name: Assert that the directory exists
  ansible.builtin.assert:
    that:
      - dir_stat.stat.exists
    fail_msg: "The directory {{ __tmp_elastic_directory }} does not exist."
