# roles/elastic_agent/tasks/installation/installation/02_install_agent.yaml

---
- block:
  - name: "Set proxy argument if defined"
    ansible.builtin.set_fact:
      proxy_cmd_arg: "{{ (__elastic_proxy_url is defined) | ternary('--proxy-url=' ~ __elastic_proxy_url, '') }}"

  - name: "Enroll Elastic Agent with Fleet (Install)"
    ansible.builtin.shell:
      chdir: "{{ __tmp_elastic_directory }}"
      cmd: >
        ./elastic-agent install
        --url={{ __elastic_console_url }}
        --enrollment-token={{ __elastic_enrollment_token }}
        {{ proxy_cmd_arg }}
        --insecure
        --non-interactive
    register: install_result
    changed_when: install_result.rc == 0
    
  - name: "Ensure Elastic Agent service is started and enabled on boot"
    ansible.builtin.systemd:
      name: elastic-agent
      state: started
      enabled: yes

  always:
  - name: "Cleanup {{ __tmp_elastic_directory }}"
    ansible.builtin.file:
      path: "{{ __tmp_elastic_directory }}"
      state: absent  
