# roles/tools/tasks/server_manual_patching/main.yaml

---
- name: Load server_manual_patching vars
  ansible.builtin.include_vars:
    file: "server_manual_patching.yaml"

- name: Initialize host data for the report
  ansible.builtin.set_fact:
    host_csv_data:
      hostname: "{{ inventory_hostname }}"
      status: "PENDING"
      action: "None"
      centreon_service_ko: ""
    snapshot_name: "LAF - Manual Patching - {{ '%Y%m%d_%H%M' | strftime }}"

- name: Define global report name
  ansible.builtin.set_fact:
    report_path: "{{ (role_path + '/../../export') | realpath }}"
  run_once: true

- name: Include Centreon tasks
  ansible.builtin.include_tasks: centreon/00_main.yaml
  vars:
    centreon_action: "set_downtime"

- name: Include host tasks (snapshot creation)
  ansible.builtin.include_tasks: vcenter/00_main.yaml
  vars:
    vcenter_action: "create_snapshot"

- name: Include host tasks
  ansible.builtin.include_tasks: host/00_main.yaml

- name: Include Centreon tasks
  ansible.builtin.include_tasks: centreon/00_main.yaml
  vars:
    centreon_action: "verify_services"

- name: Include host tasks (snapshot deletion)
  ansible.builtin.include_tasks: vcenter/00_main.yaml
  vars:
    vcenter_action: "delete_snapshot"
  when: host_csv_data.status != 'FAILED'

- name: Generate global csv_content variable
  ansible.builtin.set_fact:
    csv_content: |
      sep=,
      Hostname,Status,Action,Services Status
      {% for host in ansible_play_hosts_all -%}
      {% set hdata = hostvars[host].get('host_csv_data', {}) -%}
      {% if hdata.hostname is defined -%}
      {{ hdata.hostname }},{{ hdata.status }},{{ hdata.action }},"{{ hdata.centreon_service_ko | trim | default('OK', true) }}"
      {% else -%}
      {{ host }},UNREACHABLE,Host unreachable,N/A
      {% endif -%}
      {% endfor %}
  run_once: true
  delegate_to: localhost
  become: false

- name: "Ensure export directory exists"
  ansible.builtin.file:
    path: "{{ report_path }}"
    state: directory
    mode: '0755'
  run_once: true
  delegate_to: localhost

- name: Save the CSV file on the Ansible controller
  ansible.builtin.copy:
    content: "{{ csv_content }}"
    dest: "{{ report_path }}/patching_report_{{ '%Y%m%d_%H%M' | strftime }}.csv"
  run_once: true
  delegate_to: localhost
  become: false
