# roles/redhat_idm/tasks/manage/users/disabling/disable_user.yaml

---
- block:
  - name: Disabling IPA user {{ username }} on {{ ipa_server }}
    delegate_to: "{{ ipa_server }}"
    redhat.rhel_idm.ipauser:
      name: "{{ username }}"
      state: disabled
      ipaadmin_principal: "{{ ipa_user }}"
      ipaadmin_password: "{{ ipa_pass }}"
    register: user_disabling_result

  - name: Set user_status after disabling
    ansible.builtin.set_fact:
      user_status: "{{ 'Disabled' if user_disabling_result.changed else 'Already disabled' }}"

  - name: Update mail_content based on disabling status
    ansible.builtin.set_fact:
      mail_content: |
        {{ mail_content }}
        {% if user_disabling_result.changed %}
        {{ ipa_domain }} - {{ username }} account has been correctly disabled.<br>
        {% else %}
        <b>{{ ipa_domain }} - {{ username }} account was already disabled.</b><br>
        {% endif %}

  rescue:
  - name: Set user_status on disabling error
    ansible.builtin.set_fact:
      user_status: "Error: {{ user_disabling_result.msg | default(ansible_failed_result.msg | default('Unknown error')) | truncate(120) }}"

  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        <b>{{ ipa_domain }} - ⚠️ Failed to disable {{ username | default('username-var') }} account.</b><br>
        <pre style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ccc;">
        {{ user_disabling_result.msg | default(ansible_failed_result.msg | default('No msg captured')) }}
        </pre>
