# roles/redhat_idm/tasks/manage/users/disabling/02_loop_on_users.yaml

---
- name: Inclure disable user tasks
  ansible.builtin.include_tasks: disable_user.yaml

- name: Append result data to csv
  ansible.builtin.set_fact:
    csv_lines: "{{ csv_lines }}{{ username }},\
                {{ 'Disabled' if user_disabling_result.changed | default(false) else 'Doesn''t exist on this IPA' }},\
                {{ client_id }},\
                {{ ipa_domain }};"
