# roles/redhat_idm/tasks/manage/users/disabling/loop_on_users.yaml

---
- name: Set username from loop var
  ansible.builtin.set_fact:
    username: "{{ loop_username }}"

- name: Include disable user tasks
  ansible.builtin.include_tasks: disable_user.yaml

- name: Append result to rows
  ansible.builtin.set_fact:
    result_rows: "{{ result_rows + [row] }}"
  vars:
    row:
      username: "{{ username }}"
      status: "{{ user_status }}"
      client_id: "{{ client_id }}"
      ipa_domain: "{{ ipa_domain }}"
