# roles/redhat_idm/tasks/utils/fetch_pmp_password.yaml

---
- block:
  - name: Retrieve Password from PMP (Filtered by Name and Type)
    ansible.builtin.shell: |
      # 1. Get Resource ID (Regex match NAME + Exact match TYPE)
      RESOURCE_ID=$(curl -s -k -X GET \
        -H "AUTHTOKEN:{{ __pmp_api_token }}" \
        "{{ __pmp_api_url }}/resources" \
        | jq -r '.operation.Details[] | select( (."RESOURCE NAME" | tostring | test("{{ pmp_resource_name }}")) and (."RESOURCE TYPE" == "Comm Cli") ) | ."RESOURCE ID"' | head -n 1)
      # Remove "and (."RESOURCE TYPE" == "Comm Cli") if you don't want a communication password"

      # 2. Get Account ID
      ACCOUNT_ID=$(curl -s -k -X GET \
        -H "AUTHTOKEN:{{ __pmp_api_token }}" \
        "{{ __pmp_api_url }}/resources/${RESOURCE_ID}/accounts" \
        | jq -r '.operation.Details["ACCOUNT LIST"][0]["ACCOUNT ID"]')

      # 3. Get Password
      curl -s -k -X GET \
        -H "AUTHTOKEN:{{ __pmp_api_token }}" \
        "{{ __pmp_api_url }}/resources/${RESOURCE_ID}/accounts/${ACCOUNT_ID}/password" \
        | jq -r '.operation.Details["PASSWORD"]'
    register: pmp_result
    changed_when: false
    no_log: true
    retries: 3
    delay: 5
    until: pmp_result.rc == 0 and pmp_result.stdout | length > 0

  - name: Set final password variable
    ansible.builtin.set_fact:
      pmp_fetched_password: "{{ pmp_result.stdout }}"
    no_log: true

  rescue:
  - name: Fill mail_content with error message
    ansible.builtin.set_fact:
      mail_content: |-
        {{ mail_content }}
        An error occur when trying to get password from PMP.<br>
        <pre style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ccc;">
        {{ pmp_result.stderr_lines | default(['No stderr captured']) | join('\n') }}
        </pre>
