# roles/redhat_tomcat/tasks/install/main.yaml

---
- name: "Install {{ item }}"
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
    disable_gpg_check: true
  loop:
    - "{{ __java_package }}"
    - "{{ __tomcat_package }}"

- name: Ensure Tomcat starts on boot and is running
  ansible.builtin.systemd:
    name: tomcat
    enabled: yes
    state: started
  become: yes
